backend = "xrender";
vsync = true;
use-damage = true;

animations = true;

animation-stiffness-in-out = 380;
animation-damping = 25;

animation-for-open-window = "zoom";
animation-for-unmap-window = "zoom";
animation-for-transient-window = "slide-down";

animation-for-workspace-switch-in = "zoom";
animation-for-workspace-switch-out = "zoom";

fading = false;
corner-radius = 0;
blur-background = false;

wintypes:
{
  tooltip = { shadow = false; };
  popup_menu = { shadow = false; };
  dropdown_menu = { shadow = false; };
  menu = { animation = "fade"; };
};

active-opacity = 1.0;
inactive-opacity = 0.8;
frame-opacity = 1.0;
inactive-opacity-override = false;

focus-exclude = [
  "class_g = 'Cairo-clock'",
  "override_redirect = true"
];

shadow = true;
shadow-radius = 8;
shadow-offset-x = -8;
shadow-offset-y = -8;
shadow-opacity = 0.65;

shadow-exclude = [
  "class_g = 'Rofi'",
  "class_g = 'rofi'",
  "_GTK_FRAME_EXTENTS@:c"
];
